on:
  workflow_call:
    cacheBy:
      type: string
      required: false
      default: pnpm
jobs:
  ci:
    runs-on: ubuntu-latest
    name: Setup

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: registry
      HIVE_TOKEN: ${{ secrets.HIVE_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_API_URL: ${{ secrets.TURBO_API_URL }}
      TURBO_REMOTE_ONLY: 'true'

    services:
      postgres:
        image: postgres:13.1-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: registry
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: ${{ inputs.cacheBy }}

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Create Database
        working-directory: packages/services/storage
        run: pnpm db:create

      - name: Migrate Database
        working-directory: packages/services/storage
        run: pnpm db:migrator up

      - name: Generate Database Types
        working-directory: packages/services/storage
        run: pnpm db:generate

      - name: Setup Turbo
        run: node ./scripts/turborepo-setup.js
